---
- hosts: localhost
  vars:
    releasever: 40
  module_defaults:
    ansible.builtin.dnf:
      releasever: "{{ releasever }}"
  roles:
    - base-packages
    - flatpak-packages
    - base-services
    - nvim
    - grub-config
