- name: Disable wifi deep sleep to avoid disconnects on wifi6
  ansible.builtin.copy:
    src: iwl.conf
    dest: /etc/modprobe.d
    owner: root
    group: root
    mode: '0644'
    backup: yes
  tags: [never, axwifi]


- name: Recreate initrd to apply modprobe settings
  ansible.builtin.shell: dracut --force
  args:
    executable: /bin/bash
  tags: [never, axwifi]
