- name: Install grub-btrfs
  dnf:
    name: grub-btrfs
    state: latest
  ignore_errors: yes

- name: Set grub-btrfs defaults
  copy:
    src: grub-btrfs/config
    dest: /etc/default/grub-btrfs/config
    owner: root
    group: root
    mode: 0644

- name: Edit grub-btrfs.path systemd unit file
  copy:
    src: grub-btrfs/systemd/grub-btrfs.path
    dest: /usr/lib/systemd/system/grub-btrfs.path
    owner: root
    group: root
    mode: 0644

- name: Add power trigger for grub update
  copy:
    src: grub-btrfs/systemd/grub-btrfs-power-trigger.serivce
    dest: /usr/lib/systemd/system/grub-btrfs-power-target.service
    owner: root
    group: root
    mode: 0644


