- name: Copy dconf
  copy:
    src: dconf
    dest: /tmp/dconf
  tags: never

- name: Load dconf defaults (force it)
  shell:
    cmd: dconf load -f / < /tmp/dconf
  tags: never

- name: Disable version validation \#justrawhidethings
  ansible.builtin.command: gsettings set org.gnome.shell disable-extension-version-validation "true" 

