- name: Set grub timeout
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: 'GRUB_TIMEOUT=.*'
    line: 'GRUB_TIMEOUT=10'

- name: Set timeout to menu
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_TIMEOUT_STYLE=.*'
    line: 'GRUB_TIMEOUT_STYLE="menu"'

- name: Regenerate grub.cfg
  ansible.builtin.shell:
    cmd: grub2-mkconfig -o /boot/grub2/grub.cfg

