- name: Enable qgroups for all subvolumes
  ansible.builtin.shell:
    cmd: |
      btrfs subvolume list / | cut -d' ' -f2 | xargs -I{} -n1 btrfs qgroup create 0/{} /

- name: Setup qgroups for partitions.
  ansible.builtin.shell:
    cmd: |
      btrfs qgroup limit -e 140000000000 / && #Use bytes because samsung ssd is 1000mb/gb
      btrfs qgroup limit -e 25000000000 /var &&
      btrfs qgroup limit -e 10000000000 /var/log &&
      btrfs qgroup limit -e 323000000000 /home
