- name: Install nvim
  dnf:
    name:
      - neovim
      - fzf
    state: latest

- name: Make tempdir for nvim config pull and install
  ansible.builtin.tempfile:
    state: directory
    suffix: nvim
  register: nvim_tmpdir

- name: Pull nvim-config from github and install
  shell: |
    git clone https://github.com/Smurf/nvim-config.git "{{ nvim_tmpdir }}"
    cd "{{ nvim_tmpdir }}"
    ./global-setup.sh

