- name: Install nvim
  dnf:
    name:
      - nvim
      - fzf
    state: latest

- name: Pull nvim-config from github as {{ default_user }}
  become: true
  become_user: '{{ default_user }}'
  shell: |
    git clone https://github.com/Smurf/nvim-config.git /tmp/nvim-config
    cd /tmp/nvim-config
    ./setup.sh

