- name: Enable Google Chrome repo
  yum_repository:
    name: google-chrome
    description: Google Chrome repo
    baseurl: https://dl.google.com/linux/chrome/rpm/stable/x86_64
    gpgkey: https://dl.google.com/linux/linux_signing_key.pub
    enabled: yes
    gpgcheck: yes
    state: present

- name: Install rpmfusion free
  ansible.builtin.dnf:
    name: https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ releasever }}.noarch.rpm
    state: present

- name: Install rpmfusion nonfree
  ansible.builtin.dnf:
    name: https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ releasever }}.noarch.rpm
    state: present
