- name: Refresh dnf cache
  dnf:
    update_cache: yes

- name: Remove packagekit and gnome-software
  dnf:
    name:
      - PackageKit
      - gnome-software
    state: removed

- name: Install networking utilities
  dnf:
    name:
      - nmap
      - telnet
      - openvpn
    state: present

- name: Install virtualization utilities
  dnf:
    name:
      - libvirt
      - virt-manager
    state: present

- name: Install/Update browsers
  dnf:
    name:
      - google-chrome-stable
      - firefox
    state: latest

- name: Install system utilites
  dnf:
    name:
      - file-roller
      - flatpak
      - rsyslog
      - btrfsmaintenance
    state: present

- name: Install Gnome utilities
  dnf:
    name:
      - gnome-tweaks
      - gnome-extensions-app
      - gnome-shell-extension-appindicator
    state: present

- name: Swap ffmpeg
  ansible.builtin.shell: dnf swap ffmpeg-free ffmpeg -y

- name: Install Development Tools
  dnf:
    name: 
      - '@development-tools'
      - rpm-build
      - nodejs
    state: present
