- name: Refresh dnf cache
  dnf:
    update_cache: yes

- name: Remove packagekit
  dnf:
    name:
      - PackageKit
    state: removed

- name: Install networking utilities
  dnf:
    name:
      - nmap
      - telnet
      - openvpn
    state: latest

- name: Install QOL utilities
  dnf:
    name:
      - guake
      - flameshot

- name: Install Remote access utilities
  dnf:
    name:
      - remmina
      - remmina-plugins-rdp
      - remmina-plugins-vnc
    state: latest

- name: Install browsers
  dnf:
    name:
      - google-chrome-stable
      - firefox
    state: latest

- name: Install system utilites
  dnf:
    name:
      - intel-media-driver
      - file-roller
      - flatpak
      - gnome-tweaks
      - gnome-extensions-app
      - gnome-shell-extension-appindicator
    state: latest

- name: Install ffmpeg
  dnf:
    name: 
      - ffmpeg
      - ffmpeg-libs
    state: latest

- name: Install Development TOols
  dnf:
    name: 
      - '@development-tools'
      - rpm-build
    state: latest
