- name: Install Kernel-Vanilla Stable
  yum:
    name: kernel*vanilla*
    state: latest

- name: Remove git kernels but not kernel headers
  shell:
    cmd: |
      rpm -qa | grep -i kernel.*git.* | grep -v headers | xargs $(which rpm) -e

- name: Remove rc kernels but not kernel headers
  shell:
    cmd: |
      rpm -qa | grep -i kernel.*rc.* | grep -v headers | xargs $(which rpm) -e


- name: Exclude git and rc kernels from being updated
  ansible.builtin.lineinfile:
    path: /etc/dnf/dnf.conf
    regexp: '^excludepkgs=.*'
    line: 'excludepkgs=kernel*git* kernel*rc* kernel*debug*'

- name: Regenerate grub.cfg
  shell: 
    cmd: grub2-mkconfig -o /boot/efi/EFI/fedora/grub.cfg

